# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image and Deploy in Azure AKS

on:
  push:
    branches:
      - main
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build & push Docker image for Backend
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: syahmiahmad/feedmepos-backend
          tags: latest
          registry: docker.io
          directory: backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & push Docker image for Frontend
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: syahmiahmad/feedmepos-frontend
          tags: latest
          registry: docker.io
          directory: frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  deploy_to_aks:
    name: Deploying to Azure AKS
    needs: "push_to_registry"
    runs-on: ubuntu-latest
    steps:
      - name: setup kubectl cli
        uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: akstest
          resource-group: akstest-rg

      - uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: docker.io
          container-registry-username: ${{ secrets.DOCKER_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1.4
        with:
          action: deploy
          manifests: |
            deployment/backend.yml
            deployment/frontend.yml
          images: |
            syahmiahmad/feedmepos-backend:latest
            syahmiahmad/feedmepos-frontend:latest
          imagepullsecrets: |
            demo-k8s-secret
